# Generated by Django 5.1.4 on 2025-01-09 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 14, 46, 9, 922986, tzinfo=datetime.timezone.utc)),
        ),
    ]
