# Generated by Django 5.1.4 on 2025-01-09 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tokentoemail_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='1L4ULP62gLpFDMOIE2ZL6dgHeNo0gHWE', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 16, 1, 27, 686794, tzinfo=datetime.timezone.utc)),
        ),
    ]
