# Generated by Django 5.1.4 on 2025-01-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_note_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-is_pinned']},
        ),
    ]
