# Generated by Django 5.1.4 on 2025-01-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tokentoemail_alter_custom_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='telegram_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
