# Generated by Django 5.1.4 on 2025-01-11 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tokentoemail_salt_alter_tokentoemail_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 19, 39, 59, 687943, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='5YDaCJPQl6zLMPDfuhPExlbdxCkzxeXY', editable=False, max_length=32),
        ),
    ]
