# Generated by Django 5.1.4 on 2025-01-05 18:49

import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_note_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(max_length=7, validators=[tasks.validators.validate_hex_color]),
        ),
    ]
