# Generated by Django 5.1.4 on 2025-01-11 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tokentoemail_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentoemail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 20, 57, 13, 381439, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='e8eq1EMNypiKJJyn85xCaivusTEbUoZQ', editable=False, max_length=32),
        ),
    ]
