# Generated by Django 5.1.4 on 2025-01-15 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tokentoemail_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='fa_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 16, 51, 39, 425183, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='dOBtGJJASNHuIsdinTpNTh4G500tgkLS', editable=False, max_length=32),
        ),
    ]
