# Generated by Django 5.1.4 on 2025-01-15 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_custom_user_fa_2_alter_tokentoemail_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 17, 7, 55, 50031, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='7eooLPf91UrNNvbYs2PEJfS3wJZcHBgt', editable=False, max_length=32),
        ),
    ]
