# Generated by Django 5.1.4 on 2025-01-28 18:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_custom_user_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 18, 34, 55, 380427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='c6x5txhqtlLnllxaj8xa1lXPqBPGsBXy', editable=False, max_length=32),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short description (max 255 chars)', max_length=255, verbose_name='Title')),
                ('content', models.TextField(help_text='Detailed message body', verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Initial creation timestamp', verbose_name='Creation Date')),
                ('is_read', models.BooleanField(default=False, help_text='Has the user viewed the notification?', verbose_name='Read Status')),
                ('is_repeating', models.BooleanField(default=False, help_text='Does this notification recur?', verbose_name='Repeating')),
                ('repeat_type', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom Schedule')], help_text='Select recurrence pattern', max_length=10, null=True, verbose_name='Repeat Type')),
                ('repeat_params', models.JSONField(blank=True, help_text='Custom parameters in JSON format. For custom type, use: {"interval": number, "unit": "days|weeks|months|years"}', null=True, verbose_name='Repeat Parameters')),
                ('next_notification_date', models.DateTimeField(blank=True, help_text='Next scheduled dispatch time', null=True, verbose_name='Next Occurrence')),
                ('last_notification_date', models.DateTimeField(blank=True, help_text='Timestamp of most recent dispatch', null=True, verbose_name='Last Sent')),
                ('is_active', models.BooleanField(default=True, help_text='Is this notification currently active?', verbose_name='Active')),
                ('user', models.ForeignKey(help_text='Recipient of the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='tasks_notif_user_id_639282_idx'), models.Index(fields=['next_notification_date'], name='tasks_notif_next_no_23ba3b_idx')],
            },
        ),
    ]
