# Generated by Django 5.1.4 on 2025-01-29 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tokentoemail_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_of_note',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 20, 39, 32, 145763, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='4aX3WW6Ep7aMHRl93H22rvwtzSJnqwlw', editable=False, max_length=32),
        ),
    ]
