# Generated by Django 5.1.4 on 2025-01-29 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_note_date_of_note_alter_tokentoemail_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_of_note',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 20, 46, 3, 483445, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='8I4XWvGS37R3Jx5i7YZcgz3hxgvwDdOt', editable=False, max_length=32),
        ),
    ]
