# Generated by Django 5.1.4 on 2025-02-01 14:28

import datetime
import django.db.models.deletion
import tasks.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_tokentoemail_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-is_pinned'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='tokentoemail',
            options={'verbose_name': 'Токен для подтверждения почты', 'verbose_name_plural': 'Токены для подтверждения почты'},
        ),
        migrations.AlterField(
            model_name='note',
            name='date_changed',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_of_note',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заметки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Статус закреплённости'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='tasks.tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(max_length=7, validators=[tasks.validators.validate_hex_color], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='code',
            field=models.CharField(editable=False, max_length=6, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 14, 38, 23, 213463, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения токена'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Статус подтверждения почты'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='pKqVNdka9Ey3xcS2nDsEu1oiNkvCNFdj', editable=False, max_length=32, verbose_name='Соль'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='token_hash',
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name='Хэш токена'),
        ),
    ]
