# Generated by Django 5.1.4 on 2025-02-16 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_note_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Статус нахождения в архиве'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 13, 48, 39, 961178, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения токена'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='VEsIYWfqDIuGj09l2oUO7rBvSZVfDfVS', editable=False, max_length=32, verbose_name='Соль'),
        ),
    ]
