# Generated by Django 5.1.4 on 2025-02-25 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_note_is_archived_alter_tokentoemail_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', help_text='Choose your preferred language for the site.', max_length=2, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Choose your preferred theme for the site (light or dark).', max_length=10, verbose_name='Preferred Theme'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 21, 27, 24, 632623, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения токена'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='dxtVUUKcUmcBjj6r732MQNX2QyOGK6DO', editable=False, max_length=32, verbose_name='Соль'),
        ),
    ]
