# Generated by Django 5.1.4 on 2025-02-27 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_custom_user_language_custom_user_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 20, 21, 30, 962818, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения токена'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='o15r3xfCxtkuRAjoEqWCOc8x8ge3FuBE', editable=False, max_length=32, verbose_name='Соль'),
        ),
    ]
