# Generated by Django 5.1.4 on 2025-02-27 20:18

import datetime
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_custom_user_timezone_alter_tokentoemail_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50, validators=[tasks.models.validate_timezone]),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 20, 28, 54, 940298, tzinfo=datetime.timezone.utc), verbose_name='Дата истечения токена'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='sfOhAIuRmYK3PV6SUtK1zWnACYGRKGVK', editable=False, max_length=32, verbose_name='Соль'),
        ),
    ]
