# Generated by Django 5.1.4 on 2025-05-25 13:48

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_custom_user_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentoemail',
            name='expires_at',
            field=models.DateTimeField(default=tasks.models.default_token_expiration, verbose_name='Дата истечения токена'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='BVzRyejEjny3JPLw9bsxl9I8RT8bH1tx', editable=False, max_length=32, verbose_name='Соль'),
        ),
    ]
