# Generated by Django 5.1.4 on 2025-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_tokentoemail_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='emAsSx79OvV1LyJIPKUnEX9LIfEYXKzM', editable=False, max_length=32, verbose_name='Соль'),
        ),
    ]
