# Generated by Django 5.1.4 on 2025-06-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_tokentoemail_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='AZgkmw8NW5lqYd2u4pDhNe9n4Xpwkakg', editable=False, max_length=32, verbose_name='Соль'),
        ),
    ]
