# Generated by Django 5.1.4 on 2025-06-29 00:51

import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_tokentoemail_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(blank=True, max_length=7, validators=[tasks.validators.validate_hex_color], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='P6iiNU8rqyoLZvyaGKSd0e9vjDUFCJci', editable=False, max_length=32, verbose_name='Соль'),
        ),
    ]
