# Generated by Django 5.1.4 on 2025-07-07 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_tag_colour_alter_tokentoemail_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custom_user',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Demo account'),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='uXhOczizLEeB8MIs7BVCpno0yTVaolAh', editable=False, max_length=32, verbose_name='Соль'),
        ),
    ]
