# Generated by Django 5.1.4 on 2025-07-07 16:13

import datetime
import django.db.models.deletion
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('tasks', '0021_custom_user_created_at_custom_user_is_demo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expires', models.DateTimeField(default=datetime.datetime(2025, 7, 7, 18, 13, 18, 131711, tzinfo=datetime.timezone.utc))),
            ],
            bases=('authtoken.token',),
        ),
        migrations.AlterModelManagers(
            name='custom_user',
            managers=[
                ('objects', tasks.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='GrcIrTjHM6MhsRIFvNlnmMaPrcwrfwne', editable=False, max_length=32, verbose_name='Соль'),
        ),
    ]
