# Generated by Django 5.1.4 on 2025-07-07 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_expiringtoken_alter_custom_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringtoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 18, 46, 28, 749896, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='rJutD2j02kMOydrELHiKjWIAVwYBx983', editable=False, max_length=32, verbose_name='Соль'),
        ),
    ]
