# Generated by Django 5.1.4 on 2025-08-07 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_alter_expiringtoken_expires_alter_tokentoemail_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_deliting',
            field=models.BooleanField(default=False, verbose_name='Статус удаления'),
        ),
        migrations.AlterField(
            model_name='expiringtoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 8, 0, 36, 32, 872460, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='HAEChDfvMWkWNlNRk4iSnlsO0kzsT1E1', editable=False, max_length=32, verbose_name='Соль'),
        ),
    ]
