# Generated by Django 5.1.4 on 2025-08-28 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_note_is_deliting_alter_expiringtoken_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringtoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 2, 39, 36, 678851, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokentoemail',
            name='salt',
            field=models.CharField(default='xsLuzBqaJI8Jxl14GfPDHPY1frA9lHdj', editable=False, max_length=32, verbose_name='Соль'),
        ),
    ]
