"""
Django settings for SdelayDelo project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import sys
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOGS_DIR = os.path.join(BASE_DIR, "logs")

# Создайте папку logs если её нет
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TESTING = sys.argv[1:2] == ["test"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    'corsheaders',
    "rest_framework.authtoken",
    "drf_spectacular",
    "tasks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "SdelayDelo.middlewares.ErrorTrackingMiddleware",
    "SdelayDelo.middlewares.MediaServerMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',

]

# CORS_ALLOWED_ORIGINS = [
#     'http://127.0.0.1:5173',
# ]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = "SdelayDelo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SdelayDelo.wsgi.application"

ERROR_THRESHOLD = 10
BAN_DURATION_MINUTES = 3 * 60
ERROR_WINDOW_MINUTES = 10

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "myapp_filter": {
            "()": "django.utils.log.CallbackFilter",
            "callback": lambda record: record.name.startswith(("SdelayDelo", "tasks")),
        }
    },
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "debug_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "debug.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
            "filters": ["myapp_filter"],
        },
        "info_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "info.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
            "filters": ["myapp_filter"],
        },
        "warning_file": {
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "warnings.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
            "filters": ["myapp_filter"],
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "errors.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
            "filters": ["myapp_filter"],
        },
    },
    "loggers": {
        "django": {
            "handlers": ["debug_file", "info_file", "warning_file", "error_file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["debug_file", "info_file", "warning_file", "error_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "SdelayDelo": {
            "handlers": ["debug_file", "info_file", "warning_file", "error_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "tasks": {
            "handlers": ["debug_file", "info_file", "warning_file", "error_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "tasks.custom_user"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "4/m",
        "user": "10/m",
        "whoami": "5/m",
        "note_and_tag_read": "300/m",
        "note_and_tag_write": "30/m",
        "icon": "5/min",
    },
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1", "v2", "v3"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


if TESTING or DEBUG:
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        "whoami": None,
        "anon": None,
        "user": None,
        "icon": None,
        "note_and_tag_read": None,
        "note_and_tag_write": None,
    }


try:
    from .local_settings import *
except ImportError:
    print(
        "Local settings file not found. Please create one based on local_settings.py.example"
    )
    sys.exit(1)
except SyntaxError:
    print(
        "Local settings file is not full. Please check if local_settings.py have all information(especially email)"
    )
    sys.exit(1)


ICON_MEDIA_PATH = "icons"
MEDIA_ROOT = "media"
MEDIA_URL = "/media/"
FILE_ROOT = "files"
FILE_URL = "/files/"

if TESTING:
    from .settings_test import *
